version: 2
updates:
  # Enable version updates for GitHub Actions only
  # Go modules are handled by the custom dependencies workflow for better testing control
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"  # Avoid conflict with dependencies workflow (Monday)
      time: "10:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    reviewers:
      - "@terraform-provider-azurecaf/maintainers"
    # Group related updates together
    groups:
      github-actions:
        patterns:
          - "*"
