name: Dependency Updates

on:
  schedule:
    - cron: '0 8 * * 1' # Run every Monday at 8 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  go-mod-tidy:
    name: Update Go Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache: true

      - name: Check for go.mod file
        id: check_gomod
        run: |
          if [ -f "go.mod" ]; then
            echo "EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "EXISTS=false" >> $GITHUB_OUTPUT
            echo "::error::go.mod file not found, cannot update dependencies"
            exit 1
          fi

      - name: Update dependencies
        if: steps.check_gomod.outputs.EXISTS == 'true'
        id: update_deps
        run: |
          # Capture current deps state
          cp go.mod go.mod.old
          cp go.sum go.sum.old
          
          # Update deps
          go get -u ./...
          go mod tidy
          
          # Check if any changes were made
          if diff -q go.mod go.mod.old && diff -q go.sum go.sum.old; then
            echo "DEPS_CHANGED=false" >> $GITHUB_OUTPUT
            echo "No dependency updates needed."
          else
            echo "DEPS_CHANGED=true" >> $GITHUB_OUTPUT
            echo "Dependencies were updated."
          fi
        continue-on-error: true

      - name: Test with updated dependencies
        if: steps.update_deps.outputs.DEPS_CHANGED == 'true'
        id: test_updated
        run: |
          go test -v ./... -count=1 || echo "TESTS_PASSED=false" >> $GITHUB_OUTPUT
          echo "TESTS_PASSED=true" >> $GITHUB_OUTPUT
        continue-on-error: true
          
      - name: Revert changes if tests fail
        if: steps.test_updated.outputs.TESTS_PASSED == 'false'
        run: |
          echo "Tests failed with updated dependencies, reverting changes."
          mv go.mod.old go.mod
          mv go.sum.old go.sum
          echo "DEPS_CHANGED=false" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.update_deps.outputs.DEPS_CHANGED == 'true' && steps.test_updated.outputs.TESTS_PASSED != 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update Go dependencies'
          title: 'chore: update Go dependencies'
          body: |
            This PR updates Go dependencies and runs `go mod tidy`.
            
            These updates were automatically generated by the dependency update workflow.
            
            All tests passed with the updated dependencies.
          branch: update-dependencies
          base: main
          delete-branch: true
          labels: |
            dependencies
            automated pr