name: Documentation

on:
  push:
    branches: [main]
    paths:
      - '**/*.go'
      - '**/*.md'
  pull_request:
    branches: [main]
    paths:
      - '**/*.go'
      - '**/*.md'
  workflow_dispatch:

jobs:
  terraform-docs:
    name: Validate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Only set ref if this is a PR
      - name: Setup PR ref
        if: github.event_name == 'pull_request'
        run: |
          echo "CHECKOUT_REF=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Set up git identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Check if examples directory exists
        id: check-examples-dir
        run: |
          if [ -d "examples" ]; then
            echo "EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "EXISTS=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if terraform-docs is needed
        id: check-examples-tf
        if: steps.check-examples-dir.outputs.EXISTS == 'true'
        run: |
          if ls examples/*.tf 1> /dev/null 2>&1; then
            echo "TERRAFORM_DOCS_NEEDED=true" >> $GITHUB_OUTPUT
          else
            echo "TERRAFORM_DOCS_NEEDED=false" >> $GITHUB_OUTPUT
          fi

      - name: Render terraform docs
        if: steps.check-examples-dir.outputs.EXISTS == 'true' && steps.check-examples-tf.outputs.TERRAFORM_DOCS_NEEDED == 'true'
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: examples
          output-file: README.md
          output-method: inject
          git-push: false  # Don't push changes for now
          git-commit-message: "docs: Update generated terraform docs"
          fail-on-diff: false  # Don't fail if there's a difference

      - name: Generate README for examples directory if missing
        if: steps.check-examples-dir.outputs.EXISTS == 'true'
        run: |
          if [ ! -f "examples/README.md" ]; then
            echo "# Examples for terraform-provider-azurecaf" > examples/README.md
            echo "" >> examples/README.md
            echo "This directory contains examples that demonstrate the usage of terraform-provider-azurecaf." >> examples/README.md
            echo "" >> examples/README.md
            echo "<!-- BEGIN_TF_DOCS -->" >> examples/README.md
            echo "<!-- END_TF_DOCS -->" >> examples/README.md
            echo "Generated missing README file for examples directory"
          fi

  markdown-lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          config: '{"MD013": false, "MD033": false, "MD041": false}'  # Disable line length check, allow HTML, no first line h1
          globs: |
            **/*.md
            !node_modules/**
          fix: true  # Try to fix issues where possible

      # Skip PR creation for now until workflow is stable
      # - name: Create PR for markdown fixes
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: 'docs: Fix markdown linting issues'
      #     title: 'docs: Fix markdown linting issues'
      #     body: |
      #       This PR fixes markdown linting issues identified by markdownlint.
      #       
      #       These updates were automatically generated by the documentation workflow.
      #     branch: fix-markdown-lint
      #     base: main
      #     labels: |
      #       documentation
      #       automated pr