name: E2E Tests

on:
  push:
    branches: [ 'main', '3_0' ]
  pull_request:
    branches: [ 'main', '3_0' ]

# Prevent duplicate workflow runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Build Provider
        run: |
          go build -o terraform-provider-azurecaf
          mkdir -p ~/.terraform.d/plugins/registry.terraform.io/aztfmod/azurecaf/2.0.0-preview5/linux_amd64/
          mv terraform-provider-azurecaf ~/.terraform.d/plugins/registry.terraform.io/aztfmod/azurecaf/2.0.0-preview5/linux_amd64/terraform-provider-azurecaf_v2.0.0-preview5
          chmod +x ~/.terraform.d/plugins/registry.terraform.io/aztfmod/azurecaf/2.0.0-preview5/linux_amd64/terraform-provider-azurecaf_v2.0.0-preview5

      - name: Install go-junit-report
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Run E2E Tests
        run: |
          mkdir -p test-results
          cd tests/e2e
          go test -v ./... 2>&1 | go-junit-report > ../../test-results/e2e-tests-report.xml
        env:
          TF_ACC: "1"
          GO111MODULE: "on"

      - name: Generate Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: E2E Tests Report
          path: test-results/e2e-tests-report.xml
          reporter: java-junit

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
