name: E2E Tests
on:
  pull_request:
    branches: [ main, 3_0 ]
  push:
    branches: [ main, 3_0 ]

jobs:
  e2e_test:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Run E2E tests
        env:
          TF_ACC: "1"
        run: |
          cp resourceDefinition.json tests/e2e/
          cd tests/e2e
          go test -v ./... -json > test-output.json
          go tool test2json < test-output.json > e2e-tests-report.xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: e2e-test-results
          path: tests/e2e/e2e-tests-report.xml
