name: Integration Tests
on:
  pull_request:
    branches: [ main, 3_0 ]
  push:
    branches: [ main, 3_0 ]

jobs:
  integration_test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Run integration tests
        run: |
          go test -v ./tests/integration/... -json > test-output.json
          go tool test2json < test-output.json > integration-tests-report.xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results
          path: integration-tests-report.xml
