name: Unit Tests
on:
  pull_request:
    branches: [ main, 3_0 ]
  push:
    branches: [ main, 3_0 ]

jobs:
  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Run unit tests
        run: |
          go test -v ./azurecaf/... -coverprofile=coverage.txt -covermode=atomic -json > test-output.json
          go tool test2json < test-output.json > unit-tests-report.xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: |
            unit-tests-report.xml
            coverage.txt
